# Generated by Django 4.2.20 on 2025-07-31 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Universo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nasc", models.DateField(verbose_name="data de nascimento")),
                (
                    "codigo_id",
                    models.CharField(max_length=16, unique=True, verbose_name="ID"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("habilidades", models.TextField()),
                (
                    "caracteristicas",
                    models.TextField(null=True, verbose_name="Características"),
                ),
                ("historia", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enviada_em", models.DateTimeField(auto_now_add=True)),
                ("conteudo", models.TextField(verbose_name=1500)),
                (
                    "conversa_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginas.conversa",
                    ),
                ),
                (
                    "enviada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.personagem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversa",
            name="universo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="paginas.universo"
            ),
        ),
        migrations.AddField(
            model_name="conversa",
            name="usuarios",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Combate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginas.conversa",
                    ),
                ),
                (
                    "mensagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginas.mensagem",
                    ),
                ),
            ],
        ),
    ]
