# Generated by Django 4.2.20 on 2025-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="data_nasc",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(default="fdxfeasrexr", max_length=150),
            preserve_default=False,
        ),
    ]
