# Generated by Django 4.2.20 on 2025-09-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_favoritos"),
    ]

    operations = [
        migrations.AddField(
            model_name="combate",
            name="ganhador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ganhador",
                to="paginas.personagem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="combate",
            name="perdedor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perdedor",
                to="paginas.personagem",
            ),
            preserve_default=False,
        ),
    ]
