# Generated by Django 4.2.20 on 2025-09-11 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paginas", "0003_combate_ganhador_combate_perdedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversa",
            name="usuarios",
        ),
        migrations.AddField(
            model_name="conversa",
            name="usuarios",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
