# Generated by Django 4.2.23 on 2025-09-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0004_remove_conversa_usuarios_conversa_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='user',
            new_name='criado_por',
        ),
        migrations.AddField(
            model_name='conversa',
            name='titulo',
            field=models.CharField(default='Teste', max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universo',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversa',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='características'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='historia',
            field=models.TextField(blank=True, null=True, verbose_name='história'),
        ),
        migrations.AlterField(
            model_name='universo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='universo',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='universo',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='última atualização'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
