# Generated by Django 4.2.23 on 2025-09-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_rename_user_personagem_criado_por_conversa_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='conversa',
            name='personagens',
            field=models.ManyToManyField(to='paginas.personagem', verbose_name='Personagens'),
        ),
    ]
