# Generated by Django 4.2.5 on 2025-10-29 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0006_remove_conversa_usuarios_conversa_personagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combate',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='combate',
            name='mestre_da_mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
