# Generated by Django 4.2.5 on 2025-10-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_remove_combate_mensagem_combate_mestre_da_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='universo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='paginas.universo'),
            preserve_default=False,
        ),
    ]
