# Generated by Django 4.2.5 on 2025-10-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_personagem_universo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='universo',
            field=models.ForeignKey(help_text='O Universo não poderá ser alterado após a criação do personagem.', on_delete=django.db.models.deletion.PROTECT, to='paginas.universo'),
        ),
    ]
