# Generated by Django 4.2.23 on 2025-10-31 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paginas", "0009_alter_personagem_universo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversaUsuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amigo_username",
                    models.CharField(max_length=150, verbose_name="username do amigo"),
                ),
                (
                    "amigo_codigo_id",
                    models.CharField(max_length=16, verbose_name="codigo_id do amigo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_usuarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa entre usuários",
                "verbose_name_plural": "Conversas entre usuários",
            },
        ),
        migrations.CreateModel(
            name="MensagemConversaUsuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                ("enviada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="paginas.conversausuarios",
                    ),
                ),
                (
                    "enviada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
